/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAnalytics {
  'total_users' : bigint,
  'risk_alert_counts' : { 'low' : bigint, 'high' : bigint, 'medium' : bigint },
  'chat_usage_stats' : { 'total_sessions' : bigint, 'total_messages' : bigint },
  'average_mood_score' : number,
}
export interface AdminLog {
  'action' : string,
  'admin_id' : Principal,
  'timestamp' : bigint,
}
export interface ChatMessage {
  'session_id' : bigint,
  'sentiment_score' : number,
  'created_at' : bigint,
  'sender' : MessageSender,
  'risk_score' : number,
  'message_text' : string,
}
export interface CopingTool {
  'title' : string,
  'duration' : bigint,
  'content' : string,
  'category' : string,
}
export type MessageSender = { 'ai' : null } |
  { 'user' : null };
export interface MoodEntry {
  'emotion_label' : string,
  'sentiment_score' : number,
  'created_at' : bigint,
  'journal_text' : [] | [string],
  'user_id' : Principal,
  'risk_score' : number,
  'mood_score' : bigint,
}
export interface RiskAlert {
  'resolved' : boolean,
  'source' : string,
  'created_at' : bigint,
  'user_id' : Principal,
  'trigger_reason' : string,
  'severity' : RiskLevel,
}
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'extreme' : null } |
  { 'medium' : null };
export interface UserProfile {
  'role' : string,
  'created_at' : bigint,
  'email' : string,
  'consent_given' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChatSession' : ActorMethod<[], bigint>,
  'createCopingTool' : ActorMethod<[CopingTool], bigint>,
  'deleteCopingTool' : ActorMethod<[bigint], undefined>,
  'endChatSession' : ActorMethod<[bigint], undefined>,
  'getActiveRiskAlerts' : ActorMethod<[], Array<RiskAlert>>,
  'getAdminAnalytics' : ActorMethod<[], AdminAnalytics>,
  'getAdminLogs' : ActorMethod<[], Array<AdminLog>>,
  'getAllCopingTools' : ActorMethod<[], Array<CopingTool>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAnonymizedChatSessions' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getMoodHistory' : ActorMethod<[Principal], Array<MoodEntry>>,
  'getMoodTrend' : ActorMethod<[], Array<[bigint, number]>>,
  'getRiskAlertsByUser' : ActorMethod<[Principal], Array<RiskAlert>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string, boolean], undefined>,
  'resolveRiskAlert' : ActorMethod<[Principal, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendChatMessage' : ActorMethod<[bigint, string], string>,
  'submitMoodEntry' : ActorMethod<[bigint, string, [] | [string]], undefined>,
  'updateCopingTool' : ActorMethod<[bigint, CopingTool], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];