/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CopingTool = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'content' : IDL.Text,
  'category' : IDL.Text,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'extreme' : IDL.Null,
  'medium' : IDL.Null,
});
export const RiskAlert = IDL.Record({
  'resolved' : IDL.Bool,
  'source' : IDL.Text,
  'created_at' : IDL.Int,
  'user_id' : IDL.Principal,
  'trigger_reason' : IDL.Text,
  'severity' : RiskLevel,
});
export const AdminAnalytics = IDL.Record({
  'total_users' : IDL.Nat,
  'risk_alert_counts' : IDL.Record({
    'low' : IDL.Nat,
    'high' : IDL.Nat,
    'medium' : IDL.Nat,
  }),
  'chat_usage_stats' : IDL.Record({
    'total_sessions' : IDL.Nat,
    'total_messages' : IDL.Nat,
  }),
  'average_mood_score' : IDL.Float64,
});
export const AdminLog = IDL.Record({
  'action' : IDL.Text,
  'admin_id' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'role' : IDL.Text,
  'created_at' : IDL.Int,
  'email' : IDL.Text,
  'consent_given' : IDL.Bool,
});
export const MessageSender = IDL.Variant({
  'ai' : IDL.Null,
  'user' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'session_id' : IDL.Nat,
  'sentiment_score' : IDL.Float64,
  'created_at' : IDL.Int,
  'sender' : MessageSender,
  'risk_score' : IDL.Float64,
  'message_text' : IDL.Text,
});
export const MoodEntry = IDL.Record({
  'emotion_label' : IDL.Text,
  'sentiment_score' : IDL.Float64,
  'created_at' : IDL.Int,
  'journal_text' : IDL.Opt(IDL.Text),
  'user_id' : IDL.Principal,
  'risk_score' : IDL.Float64,
  'mood_score' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChatSession' : IDL.Func([], [IDL.Nat], []),
  'createCopingTool' : IDL.Func([CopingTool], [IDL.Nat], []),
  'deleteCopingTool' : IDL.Func([IDL.Nat], [], []),
  'endChatSession' : IDL.Func([IDL.Nat], [], []),
  'getActiveRiskAlerts' : IDL.Func([], [IDL.Vec(RiskAlert)], ['query']),
  'getAdminAnalytics' : IDL.Func([], [AdminAnalytics], ['query']),
  'getAdminLogs' : IDL.Func([], [IDL.Vec(AdminLog)], ['query']),
  'getAllCopingTools' : IDL.Func([], [IDL.Vec(CopingTool)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAnonymizedChatSessions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getMoodHistory' : IDL.Func([IDL.Principal], [IDL.Vec(MoodEntry)], ['query']),
  'getMoodTrend' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Int, IDL.Float64))],
      ['query'],
    ),
  'getRiskAlertsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(RiskAlert)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'resolveRiskAlert' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendChatMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'submitMoodEntry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'updateCopingTool' : IDL.Func([IDL.Nat, CopingTool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CopingTool = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'content' : IDL.Text,
    'category' : IDL.Text,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'extreme' : IDL.Null,
    'medium' : IDL.Null,
  });
  const RiskAlert = IDL.Record({
    'resolved' : IDL.Bool,
    'source' : IDL.Text,
    'created_at' : IDL.Int,
    'user_id' : IDL.Principal,
    'trigger_reason' : IDL.Text,
    'severity' : RiskLevel,
  });
  const AdminAnalytics = IDL.Record({
    'total_users' : IDL.Nat,
    'risk_alert_counts' : IDL.Record({
      'low' : IDL.Nat,
      'high' : IDL.Nat,
      'medium' : IDL.Nat,
    }),
    'chat_usage_stats' : IDL.Record({
      'total_sessions' : IDL.Nat,
      'total_messages' : IDL.Nat,
    }),
    'average_mood_score' : IDL.Float64,
  });
  const AdminLog = IDL.Record({
    'action' : IDL.Text,
    'admin_id' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'role' : IDL.Text,
    'created_at' : IDL.Int,
    'email' : IDL.Text,
    'consent_given' : IDL.Bool,
  });
  const MessageSender = IDL.Variant({ 'ai' : IDL.Null, 'user' : IDL.Null });
  const ChatMessage = IDL.Record({
    'session_id' : IDL.Nat,
    'sentiment_score' : IDL.Float64,
    'created_at' : IDL.Int,
    'sender' : MessageSender,
    'risk_score' : IDL.Float64,
    'message_text' : IDL.Text,
  });
  const MoodEntry = IDL.Record({
    'emotion_label' : IDL.Text,
    'sentiment_score' : IDL.Float64,
    'created_at' : IDL.Int,
    'journal_text' : IDL.Opt(IDL.Text),
    'user_id' : IDL.Principal,
    'risk_score' : IDL.Float64,
    'mood_score' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChatSession' : IDL.Func([], [IDL.Nat], []),
    'createCopingTool' : IDL.Func([CopingTool], [IDL.Nat], []),
    'deleteCopingTool' : IDL.Func([IDL.Nat], [], []),
    'endChatSession' : IDL.Func([IDL.Nat], [], []),
    'getActiveRiskAlerts' : IDL.Func([], [IDL.Vec(RiskAlert)], ['query']),
    'getAdminAnalytics' : IDL.Func([], [AdminAnalytics], ['query']),
    'getAdminLogs' : IDL.Func([], [IDL.Vec(AdminLog)], ['query']),
    'getAllCopingTools' : IDL.Func([], [IDL.Vec(CopingTool)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAnonymizedChatSessions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getMoodHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MoodEntry)],
        ['query'],
      ),
    'getMoodTrend' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Int, IDL.Float64))],
        ['query'],
      ),
    'getRiskAlertsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(RiskAlert)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'resolveRiskAlert' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendChatMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'submitMoodEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateCopingTool' : IDL.Func([IDL.Nat, CopingTool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };